apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: home-dir
  name: home-dir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
