apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/bonnland/bin/kompose --file docker-compose.yml convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "8443"
      port: 8443
      targetPort: 443
  selector:
    io.kompose.service: nginx
