apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/bonnland/bin/kompose --file docker-compose.yml convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/bonnland/bin/kompose --file docker-compose.yml convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: solr
    spec:
      containers:
        - image: ckan/ckan-solr:2.10-solr9-spatial
          livenessProbe:
            exec:
              command:
                - wget
                - -qO
                - /dev/null
                - http://localhost:8983/solr/
          name: solr
          ports:
            - containerPort: 8983
              protocol: TCP
          volumeMounts:
            - mountPath: /var/solr
              name: solr-data
      restartPolicy: Always
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
