apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/bonnland/bin/kompose --file docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 8800
  selector:
    io.kompose.service: datapusher
