apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/bonnland/bin/kompose --file docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/bonnland/bin/kompose --file docker-compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:stable-alpine
          name: nginx
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: waf-dir
      restartPolicy: Always
      volumes:
        - name: waf-dir
          persistentVolumeClaim:
            claimName: waf-dir
