name: Build CKAN Docker 

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  #workflow dispatch adds a button to run on github and is useful to always have there
  workflow_dispatch:

jobs: 
  build:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2
    
    # Get the date to apply to image tag
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
      
    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v1

    -  name: NGINX build
       uses: docker/build-push-action@v2
       with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: sage-dashsearch-nginx:${{ steps.date.outputs.date }}

    -  name: PostgreSQL build
       uses: docker/build-push-action@v2
       with:
          context: ./postgresql
          file: ./postgresql/Dockerfile
          push: false
          tags: ncar/sage-dashsearch/postgres:${{ steps.date.outputs.date }}

    -  name: SOLR build
       uses: docker/build-push-action@v2
       with:
          context: ./solr
          file: ./solr/Dockerfile
          push: false
          tags: ncar/sage-dashsearch/solr:${{ steps.date.outputs.date }}
          
    -  name: CKAN build
       uses: docker/build-push-action@v2
       with:
          context: ./ckan
          file: ./ckan/Dockerfile
          build-args: |
            TOKEN=${{ secrets.REPO_TOKEN }}
          push: false
          tags: ncar/sage-dashsearch/ckan:${{ steps.date.outputs.date }}
      
